version: '3.7'

services:
  telegram_bot:
    build: .
    command: python telegram_bot.py
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped

  vk_bot:
    build: .
    command: python vk_bot.py
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
